package main

var Names = map[string]string{
	"USD": "US, dollar",
	"SEK": "Sweden, kronor",
	"ATS": "Austria, shilling",
	"AUD": "Australian, dollar",
	"BEF": "Belgien, franc",
	"BRL": "Brazilien, real",
	"CAD": "Canada, dollar",
	"CHF": "Switzerland, francs",
	"CNY": "China, yuan renminbi",
	"CYP": "Cyprus, pound",
	"CZK": "Czech Republic, koruna",
	"DEM": "Germany, mark",
	"DKK": "Denmark, krone",
	"EEK": "Estonian, kroon",
	"ESP": "Spain, pesetas",
	"EUR": "Euroland, euro",
	"FIM": "Finland, marka",
	"FRF": "France, franc",
	"GBP": "Great Britain, pound",
	"GRD": "Greece, drachmer",
	"HKD": "Hong Kong, dollar",
	"HUF": "Hungary, forint",
	"IDR": "Indonesia, rupiah",
	"IEP": "Ireland, pund",
	"INR": "India, rupee",
	"ISK": "Iceland, kronor",
	"ITL": "Italy, lire",
	"JPY": "Japan, yen",
	"KRW": "South Korea, won",
	"KWD": "Kuwait, dinar",
	"LTL": "Lithuania, litas",
	"LVL": "Latvia, lat",
	"MAD": "Morocko, dirham",
	"MXN": "Mexico, nuevo peso",
	"MYR": "Malaysia, ringgit",
	"NLG": "Dutchland, guilder",
	"NOK": "Norway, krone",
	"NZD": "New Zealand, dollar",
	"PLN": "Poland, zloty",
	"PTE": "Portugal, escudo",
	"RUB": "Russia, rouble",
	"SAR": "Saudi Arabia, riyal",
	"SGD": "Singapore, dollar",
	"SIT": "Slovenia, tolar",
	"SKK": "Slovakia, koruna",
	"THB": "Thailand, baht",
	"TRL": "Turkey, lira",
	"TRY": "Turkey, new lira",
	"ZAR": "South Africa, rand",
}
